CREATE DATABASE TREES;
-- SHOW DATABASES; -- Not supported in SQL Server
USE TREES;

CREATE TABLE TREES_INFO(
    ID INT PRIMARY KEY,
    SPECIES VARCHAR(30) NOT NULL,
    HEIGHT INT NOT NULL,
    LEAF_SIZE DECIMAL(5,2),
    STEM_LENGTH DECIMAL(8,3),
    FRUIT_NAME VARCHAR(30)
);

-- TABLES;--
SELECT COLUMN_NAME, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'TREES_INFO';
-- DESCRIBE TREES_INFO; -- Not supported in SQL Server
DROP TABLE TREES_INFO;
DROP DATABASE TREES;
